spring.application.name=ingestion-service
server.port=8081

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/finsight}

spring.kafka.bootstrap-servers=${KAFKA_BROKERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

management.endpoints.web.exposure.include=health,info,metrics